[build]
  command = "npm run build"
  publish = "public"        # ← cambia "dist" por "public" (ahí está tu index.html)
  functions = "netlify/functions"
ß
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200